### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by ReverseSystem001** [TwentyBN/20bn-realtimenet#9]
a great work！Are you willing to provide training code and training set？
Hope your reply! thks

**Comment by guillaumebrg** [comment]
Hi! Thanks for the feedback! We might release the training code at some point... but we're not actively working on it at the moment. Regarding the training data, we've already released some of it (see our [Jester](https://20bn.com/datasets/jester/v1) and [Something-something](https://20bn.com/datasets/something-something/v2) datasets) and we're planning to release more datasets soon.

**Comment by ReverseSystem001** [comment]
get! thanks

**Comment by FishEatApple** [comment]
great great work!!!!! if you provide training code,it will be greater!!!!
